### ISSUE TITLE
How to touch first view controller

### ISSUE THREAD

**Issue by gunantosteven** [martinnormark/HalfModalPresentationController#13]
Hello nice work.

![unnamed 1](https://user-images.githubusercontent.com/8141036/40525280-69d3abaa-6009-11e8-9810-564d1cccdd93.jpg)

I have issue, i hope this picture can discribed. Thanks.
can we click or touch ? i have tried to do that but still can't figure it out.

**Comment by martinnormark** [comment]
You mean you cannot drag the map there?

**Comment by gunantosteven** [comment]
yes, it looks like second view controlller cover it.

**Comment by martinnormark** [comment]
Ok, there's [an overlay](https://github.com/martinnormark/HalfModalPresentationController/blob/46f0da900f75db15d5ae7aee0bb995e809a0018b/HalfModalPresentationController/Presentation/HalfModalPresentationController.swift#L124) - that might be causing the issues.

**Comment by gunantosteven** [comment]
still not working, i have deleted before. thanks.

**Comment by gunantosteven** [comment]
other solution ?

**Comment by martinnormark** [comment]
Something must be sitting on top, try to inspect the view etc. to identify it. It's not easy to help without seeing it myself.

**Comment by gunantosteven** [comment]
I end up using container UIView. It's a little bit tricky but that's what i want.
