### ISSUE TITLE
How to run this code when i click marker in google map 

### ISSUE THREAD

**Issue by mhalsamak** [martinnormark/HalfModalPresentationController#14]
self.halfModalTransitioningDelegate = HalfModalTransitioningDelegate(viewController: self, presentingViewController: segue.destination)
        
        segue.destination.modalPresentationStyle = .custom
        segue.destination.transitioningDelegate = self.halfModalTransitioningDelegate

**Comment by martinnormark** [comment]
It should be possible to hook into an event, or add a tap gesture recognizer.
